- components/gravityforms/class-gf-convertkit.php
Closes #21
Uses Gravity Forms' built in GFAddOn::get_field_value() to get a calculated
value of the `Name (Full)` field rather than trying (and failing) to access
it directly from a form entry.
> Make `Name (Full)` field mapping work

- .github/workflows/test.yml
- tests/_support/Helper/Acceptance.php
- tests/acceptance.suite.yml
- tests/acceptance/ActivateDeactivatePluginCest.php
- tests/acceptance/AnyErrorsOnBlankInstallCest.php
- tests/acceptance/FormCest.php
- tests/acceptance/SettingCest.php
Improves test performance in GitHub Actions by running tests in parallel instead of sequentially.
Changes to tests are made to ensure that they can run in parallel by:
- Generating unique email addresses for tests, using the current date, time and PHP version
- Ensuring that the test environment is reset by the test (by way of `_before()` and `_passed()`), rather than reloading the entire database between tests
Test run time across all environments totals ~ 8 minutes, where it was previously ~ 27 minutes.
> Improve Test Performance

- .github/workflows/test.yml
- composer.json
- includes/class-ckgf-api.php
- includes/class-gfconvertkit.php
- includes/class-wp-ckgf.php
- phpstan.neon.dist
- phpstan.neon.example
[PHPStan](https://phpstan.org/blog/find-bugs-in-your-code-without-writing-tests) performs static analysis on the Plugin's PHP code.  This adds to our tests, PHP Coding Standards and WordPress Coding Standards by ensuring:
- DocBlocks declarations are valid and uniform
- DocBlocks declarations for WordPress `do_action()` and `apply_filters()` calls are valid
- Typehinting variables and return types declared in DocBlocks are correctly cast
- Any unused functions are detected
- Unnecessary checks / code is highlighted for possible removal
- Conditions that do not evaluate can be fixed/removed as necessary
This isn't a replacement for writing tests; rather, an addition to ensure our code continues to meet the high standards expected, reducing ambiguity on how code should be written and …
> Add PHPStan for Static Analysis

- convertkit.php
- includes/class-ckgf-review-request.php
- includes/class-gfconvertkit.php
- includes/class-wp-ckgf.php
- tests/_support/Helper/Acceptance.php
- tests/acceptance/FormCest.php
- tests/acceptance/ReviewRequestCest.php
- views/backend/review/notice.php
Similar to the [main ConvertKit Plugin](https://github.com/ConvertKit/convertkit-wordpress/pull/279/), adds a notification in the WordPress Administration interface requesting the user leave a 5 star review on [wordpress.org](https://wordpress.org/support/plugin/convertkit-gravity-forms/reviews/), to assist with the Plugin's ranking on search results within WordPress.
Clicking either button or the close button hides the notification for life; no other WordPress Administrator will see it.
Clicking `Yes, Leave Review` hides the notification, and opens a new browser tab at https://wordpress.org/support/plugin/convertkit-gravity-forms/reviews/?filter=5#new-post
Clicking `No, I'm having issues with ConvertKit` opens a new browser tab at https://convertkit.com/support
This notification will …
> Review Request Notification

- .github/workflows/test.yml
- tests/_support/Helper/Acceptance.php
Updates acceptance tests when creating a Gravity Form to support how Gravity Forms 2.6 select dropdown values are defined in the form editor UI, compared to 2.5 and earlier.
- `createGravityFormsForm` helper function updated to support defining select dropdown options in Gravity Forms 2.6's form editor UI.
> Testing: Support for Gravity Forms 2.6

- includes/class-gfconvertkit.php
- readme.txt
- tests/_support/Helper/Acceptance.php
Displays the ConvertKit logo / icon for notes added by this Plugin to a Gravity Forms entry.
Before:
After:
- Added check to `checkGravityFormsNotesExist`, `checkGravityFormsSuccessNotesExist` and `checkGravityFormsErrorNotesExist` helper functions to confirm that the ConvertKit logo is displayed.
> Use ConvertKit icon for entry notes

- phpstan.neon.dist
PHPStan 1.7 better detects some WordPress constants and fixes some false positives, which can be safely removed from the `phpstan.neon.dist` configuration, similar to the [main ConvertKit Plugin](https://github.com/ConvertKit/convertkit-wordpress/pull/316).
> Updated PHPStan configuration to support PHPStan 1.7

- phpstan.neon.dist
- phpstan.neon.example
Fixes PHPStan's configuration for GitHub actions by:
- Changing `scanDirectories` to scan the WordPress Plugins directory to build symbols (function definitions and constants), rather than scanning the entire WordPress installation, because the `includes` configuration already points to phpstan-wordpress' WordPress symbol definitions.  Scanning the entire WordPress installation is slower and results in [false positive errors](https://github.com/ConvertKit/convertkit-gravity-forms/runs/6817912437?check_suite_focus=true).
- Changing `ignoreErrors` to ignore some Gravity Forms symbols that aren't yet detected by PHPStan.
Existing tests should pass to confirm this PR works.
> Fix PHPStan Configuration

- .github/workflows/test.yml
- convertkit.php
- includes/class-gfconvertkit.php
- lib/class-convertkit-api.php
- lib/class-convertkit-log.php
Replaces `phpcs:ignore` comments with the specific rule to ignore, such as `phpcs:ignore PSR2.Classes.PropertyDeclaration.Underscore`.
This ensures the coding standard checks for lines containing an ignore directive will still validate the code against other coding standard rules.
Existing tests pass to confirm no breaking changes.
> Improve reasons to ignore coding standards

- .github/workflows/test.yml
- composer.json
- tests/_data/dump.sql
Runs tests against the latest WordPress version, 6.0.1, on GitHub's actions.
Updates the database dump structure to match that used by WordPress 6.0.1.
> Run tests against WordPress 6.0.1

- includes/class-gfconvertkit.php
- readme.txt
- tests/_support/Helper/Acceptance/GravityForms.php
- tests/_support/Helper/Acceptance/Plugin.php
- tests/_support/Helper/Acceptance/Roles.php
- tests/acceptance.suite.yml
- tests/acceptance/CapabilitiesCest.php
Renames the Form Settings capability from the incorrect `$_capabilities_form_page` to the correct `$_capabilities_form_settings`, as reported [here](https://wordpress.org/support/topic/capabilities-bug-2/).
Capabilities are assigned to WordPress Roles, and determine what a Role can and cannot do in WordPress.
Roles, in turn, are assigned to WordPress Users, which determines what a User can and cannot do in WordPress.
For Gravity Forms, it's possible to register three capabilities, that non-Administrator Roles can have assigned to them (Administrators always have access to all capabilities by default):
- `ckgf_convertkit_settings_page`: Permits the Role access to the Plugin's Settings page at Forms > Settings > ConvertKit
- `ckgf_convertkit_form_page`: Permits the Role access to a Form's …
> Rename, Fix and Test Capabilities

- .github/workflows/test.yml
- readme.txt
Run tests against WordPress 6.0.3, released October 17th.
Existing tests pass
> Run tests against WordPress 6.0.3

- .github/workflows/test.yml
Run tests against WordPress 6.1 RC5, head of WordPress 6.1's formal release on ~ 1st November 2022.
Existing tests pass
> Run tests against WordPress 6.1 RC5

- .github/workflows/coding-standards.yml
- .github/workflows/test.yml
Run Tests and Coding Standards against WordPress 6.1, released November 1st.
> Run Tests and Coding Standards against WordPress 6.1

- .github/workflows/coding-standards.yml
- phpcs.tests.xml
- tests/_support/AcceptanceTester.php
- tests/_support/FunctionalTester.php
- tests/_support/Helper/Acceptance.php
- tests/_support/Helper/Acceptance/ConvertKitAPI.php
- tests/_support/Helper/Acceptance/Email.php
- tests/_support/Helper/Acceptance/GravityForms.php
- tests/_support/Helper/Acceptance/Plugin.php
- tests/_support/Helper/Acceptance/Roles.php
- tests/_support/Helper/Acceptance/ThirdPartyPlugin.php
- tests/_support/Helper/Acceptance/Xdebug.php
- tests/_support/Helper/Functional.php
- tests/_support/Helper/Unit.php
- tests/_support/Helper/Wpunit.php
- tests/_support/UnitTester.php
- tests/_support/WpunitTester.php
- tests/acceptance/forms/FormCest.php
- tests/acceptance/general/ActivateDeactivatePluginCest.php
- tests/acceptance/general/AnyErrorsOnBlankInstallCest.php
- tests/acceptance/general/CapabilitiesCest.php
- tests/acceptance/general/ReviewRequestCest.php
- tests/acceptance/general/SettingCest.php
Applies coding standards for tests, as we do for the [main ConvertKit Plugin](https://github.com/ConvertKit/convertkit-wordpress/pull/380).
This PR includes whitespace fixes; a [separate PR](https://github.com/ConvertKit/convertkit-gravity-forms/pull/68) covers fixes for other coding standards in tests, which means the coding standards GitHub Action will fail at this time.
Existing tests are run.
> Tests: Apply Coding Standards

- .github/workflows/coding-standards.yml
- .github/workflows/test.yml
Uses `latest` for `wp-versions`, so that tests and coding standards always run against the latest stable release of WordPress, to save having to change the version number every time there's a WordPress update.
> Run Tests against latest stable WordPress version

- .github/workflows/test.yml
Runs tests against PHP 8.1, which is the current (and only) [actively supported version](https://www.php.net/supported-versions.php) provided by PHP.
`WP_DEBUG` is disabled when running tests against PHP 8.1, due to [this WordPress core](https://core.trac.wordpress.org/ticket/54504) issue that requires resolution to prevent `E_DEPRECATED` notices when performing HTTP requests.
Critical PHP errors and warnings will still result in test failure, however we'll need to reintroduce WP_DEBUG once WordPress resolve the above core issue.
> Run tests against PHP 8.1

- .github/workflows/coding-standards.yml
- .github/workflows/test.yml
- tests/nginx/php-8.2.conf
Runs tests against PHP 8.2, released December 8th 2022.
`WP_DEBUG` is disabled when running tests against PHP 8.2, due to [this WordPress core](https://core.trac.wordpress.org/ticket/54504) issue that requires resolution to prevent `E_DEPRECATED` notices when performing HTTP requests.
Critical PHP errors and warnings will still result in test failure, however we'll need to reintroduce WP_DEBUG once WordPress resolve the above core issue.
> Run tests against PHP 8.2

- composer.json
- includes/class-ckgf-api.php
Updates the Plugin to use the latest version of our ConvertKit WordPress Libraries, [1.2.3](https://github.com/ConvertKit/convertkit-wordpress-libraries/releases/tag/1.2.3), resolving [this issue](https://convertkit.atlassian.net/browse/T3-106).
> Use WordPress Libraries 1.2.3

- composer.json
- includes/class-gfconvertkit.php
- tests/_support/Helper/Acceptance/GravityForms.php
- tests/_support/Helper/Acceptance/Plugin.php
Implements 1.3.1 of the WordPress Libraries, resolving [this issue](https://wordpress.org/support/topic/convertkit-tags-in-woocommerce-not-in-alphabetical-order/), to ensure that Forms, Landing Pages, Tags, Broadcasts and Products are returned in alphabetical order by name.
- Added `checkSelect*Order()` helper functions to test that the order of `<select>` dropdown option are correct
> Return Resources in correct order

- .github/workflows/test.yml
- tests/wpunit.suite.yml
- tests/wpunit/APITest.php
Adds a unit test to confirm that the Plugin's name and version number is in the user-agent string when making API requests.
- `APITest`: Unit test to confirm that the correct Plugin name and version number are included in the user-agent string when making API requests.
> Test User Agent for API requests

- .github/workflows/coding-standards.yml
- .github/workflows/test.yml
Runs tests against WordPress 6.2 RC2
> Run tests against WordPress 6.2 RC2

- tests/_support/Helper/Acceptance/GravityForms.php
- tests/acceptance/forms/FormCest.php
Adds tests to confirm that an email address is (or is not) subscribed to ConvertKit, depending on how a Gravity Forms Feed's conditional logic is configured.
Created based on [this ticket](https://wordpress.org/support/topic/integration-with-gravity-forms-quiz-add-on/), to confirm that we honor Gravity Forms conditional logic.
- `FormCest:testCreateFormAndFeedWithConditionalLogicMatching`: Test that the email is subscribed to ConvertKit when the feed's conditional logic condition is met.
- `FormCest:testCreateFormAndFeedWithConditionalLogicDoesNotMatch`: Test that the email is not subscribed to ConvertKit when the feed's conditional logic is not met.
> Tests: Conditional Logic

- tests/_support/Helper/Acceptance/GravityForms.php
- tests/acceptance/forms/FormCest.php
Updates logic for creating a form in tests to be compatible with Gravity Forms 2.7.5, which introduces a modal window when adding a new form.
> Update test compatibility for Gravity Forms 2.7.5

- includes/class-gfconvertkit.php
- tests/_support/Helper/Acceptance/Plugin.php
- tests/acceptance.suite.yml
- tests/acceptance/general/SettingCest.php
Adds an API Secret field to the Plugin's settings, which will be required when [calling the `recommendations_script()` method](https://github.com/ConvertKit/convertkit-wordpress-libraries/pull/23) in a later PR.
- `setupConvertKitPlugin`: Added the API Secret field to the test, confirming correct working functionality when a valid API Secret is specified
- `testSaveInvalidAPIKey`: Test that specifying an invalid API Key returns the expected error
- `testSaveInvalidAPISecret`: Test that specifying an invalid API Secret returns the expected error
> Add API Secret Field

- .github/workflows/test.yml
- composer.json
- includes/class-gfconvertkit.php
- includes/functions.php
- tests/_support/Helper/Acceptance/GravityForms.php
- tests/_support/Helper/Acceptance/Plugin.php
- tests/acceptance/recommendations/RecommendationsCest.php
Adds an option to enable the Creator Network Recommendations to a Gravity Forms Form:
When enabled, the modal is displayed when the form is submitted:
Demonstration:
https://www.loom.com/share/4d6667a987f6484a953fd6e6cce8fff6?sid=e50a65ac-30dd-432a-bc87-2a9f834e2622
Several requirements must be met for this to work:
`Output HTML5` must be enabled in Gravity Forms (Forms > Settings > Output HTML5).  This will output email fields as `input[type=email]`, which `recommendations.js` is compatible with.
If disabled, the form setting will tell the user what they need to do:
A valid API Secret must be specified at `Forms > Settings > ConvertKit`.  1.3.6 and earlier of this Plugin only requested an API Key, but as the API endpoint to fetch the recommendations script requires an API Secret, this …
> Add Creator Network Recommendations

- .github/workflows/test.yml
- composer.json
- includes/class-gfconvertkit.php
- includes/functions.php
- tests/_support/Helper/Acceptance/GravityForms.php
- tests/_support/Helper/Acceptance/Plugin.php
- tests/acceptance/general/SettingCest.php
- tests/acceptance/recommendations/RecommendationsCest.php
Improves test performance by programmatically writing the supplied API Key, Secret and debug setting when using the `setupConvertKitPlugin()` helper method, as we do for the main ConvertKit Plugin.
Renames `testSaveValidAPICredentials ` to `testSaveValidAPIKeyAndSecret` for clarity; this test now performs the manual steps in the UI, as `setupConvertKitPlugin()` programmatically defines the API Key, Secret and debug log settings.
Before:
After:
> Tests: Improve Performance

- composer.json
- includes/class-gfconvertkit.php
- phpcs.tests.xml
- phpcs.xml
- tests/acceptance/general/ActivateDeactivatePluginCest.php
Applies changes per the upgrade guide [here](https://github.com/WordPress/WordPress-Coding-Standards/wiki/Upgrade-Guide-to-WordPressCS-3.0.0-for-Developers-of-external-standards), to support `3.0.0` of the WordPress Coding Standards rulesets, released August 21st.
This covers:
- Spacing for anonymous functions
- Renaming some exclusion rules as they have been renamed in WordPress Coding Standards `3.0.0`
> Upgrade to WordPress Coding Standards v3

- .github/workflows/coding-standards.yml
Annotates code in a PR when coding standards errors are detected by the GitHub action:
Existing tests pass
> Annotate PR errors

- composer.json
- includes/class-ckgf-api.php
Updates WordPress Libraries to [1.3.9](https://github.com/ConvertKit/convertkit-wordpress-libraries/releases/tag/1.3.9)
Removes localized error messages, as the text domain (`convertkit`) for this Plugin matches the main ConvertKit Plugin - therefore, the localized error messages supplied by the WordPress Libraries don't need to have their text domain changed.
> Updated WordPress Libraries to 1.3.9
